// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVCIZnwUEHmoTa6lmg38XLqSxhNq92vRs',
    appId: '1:695624267039:android:acaaf6562517b7367d6c2a',
    messagingSenderId: '695624267039',
    projectId: 'app-marketing-aguscele',
    storageBucket: 'app-marketing-aguscele.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO2TE_Ly4VGt5VlGegwFjeRF6OoBsyh88',
    appId: '1:695624267039:ios:53e869e9ea78e6087d6c2a',
    messagingSenderId: '695624267039',
    projectId: 'app-marketing-aguscele',
    storageBucket: 'app-marketing-aguscele.firebasestorage.app',
    iosBundleId: 'com.reelsmanager.reelsManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO2TE_Ly4VGt5VlGegwFjeRF6OoBsyh88',
    appId: '1:695624267039:ios:7521e3ba1befc5957d6c2a',
    messagingSenderId: '695624267039',
    projectId: 'app-marketing-aguscele',
    storageBucket: 'app-marketing-aguscele.firebasestorage.app',
    iosBundleId: 'com.marketingceleagus.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm3of5g6ihODDGs-Fjrsui3eb19V01PaQ',
    appId: '1:695624267039:web:ffc6adcfe06a21377d6c2a',
    messagingSenderId: '695624267039',
    projectId: 'app-marketing-aguscele',
    authDomain: 'app-marketing-aguscele.firebaseapp.com',
    storageBucket: 'app-marketing-aguscele.firebasestorage.app',
    measurementId: 'G-EL2NHDK9LC',
  );
}
